using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Edje.Bookmarks.UrlDirParser.Services.Models;

public class Bookmark
{
    public string Url { get; set; } = "#";

    public string? Title { get; set; }

    public string? Description { get; set; }

    /// <summary>
    /// Domain without suffic acts as a fuzzy tag that is used the find communities. This obviously
    /// will only sometimes work since the same name is used over various domains for different
    /// organisations and not in all cases a community has such a topic. So it is a hint to.
    /// </summary>
    public string? Domain { get; set; }

    /// <summary>
    /// The favicon url is either generated by the pregeneration or manually added
    /// </summary>
    public string? FaviconUrl { get; set; }
}