using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Edje.Bookmarks.Db.Db;

public class Url
{
    //public Url ()
    //{
    //    TermTaxonomyUrl = new HashSet<TermTaxonomyUrl>();
    //}

    [Key]
    [Column(Order = 1)]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public string Uri { get; set; } = "#";

    public string? Title { get; set; }

    public string? Description { get; set; }

    /// <summary>
    /// Domain without suffic acts as a fuzzy tag that is used the find communities. This obviously
    /// will only sometimes work since the same name is used over various domains for different
    /// organisations and not in all cases a community has such a topic. So it is a hint to.
    /// </summary>
    public string? Domain { get; set; }

    /// <summary>
    /// The favicon url is either generated by the pregeneration or manually added
    /// </summary>
    public string? FaviconUrl { get; set; }

    // invere properties

    //[InverseProperty("Url")]
    //public virtual ICollection<TermTaxonomyUrl>? TermTaxonomyUrl { get; set; }
}